server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/emergencity?sslmode=disable
    username: admin
    password: admin